server:
  port: 8087

spring:
  application:
    name: flowlong-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/flowlong_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.flowlong.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# FlowLong 配置
flowlong:
  reminder:
    cron: "0 */5 * * * ?"
  eventing:
    task: true

# Sa-Token 配置
sa-token:
  token-name: satoken
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true

logging:
  level:
    com.example.flowlong.repository: debug
