version: '3.8'

services:
  eureka-server:
    image: springcloud/eureka-server:latest
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_SERVER_ENABLE_SELF_PRESERVATION=true
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge
